In [1]:
import pandas as pd

In [2]:
import yfinance as yf
import datetime as dt

start = dt.datetime(2021, 7, 1)
end = dt.datetime(2022, 1, 27)
symbol = 'AXISBANK.NS'  # Stock symbol in uppercase

stk_data = yf.download(symbol, start=start, end=end)

[*********************100%%**********************]  1 of 1 completed

In [3]:
stk_data

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2021-07-01,750.000000,754.400024,744.500000,746.450012,743.211792,5695690
2021-07-02,747.599976,752.849976,744.000000,750.650024,747.393555,3557647
2021-07-05,757.099976,762.000000,753.400024,760.349976,757.051453,4680089
2021-07-06,757.000000,767.000000,755.200012,758.349976,755.060120,5529485
2021-07-07,755.900024,764.000000,752.250000,762.900024,759.590454,3573368
...,...,...,...,...,...,...
2022-01-19,725.200012,731.950012,718.700012,729.599976,726.434814,7746270
2022-01-20,731.049988,737.150024,722.150024,728.900024,725.737915,8505400
2022-01-21,722.000000,725.250000,708.049988,712.500000,709.409119,10689060
2022-01-24,715.000000,716.400024,688.200012,704.599976,701.543335,8812501
2022-01-25,714.000000,755.000000,708.599976,752.200012,748.936890,38088158

In [4]:
stk_data=stk_data[["Close","High","Open","Low"]]

In [5]:
from sklearn.preprocessing import MinMaxScaler
Ms = MinMaxScaler()
data1= Ms.fit_transform(stk_data)
print("Len:",data1.shape)

Len: (143, 4)

In [6]:
data1

array([[0.49149503, 0.44154881, 0.50898197, 0.54381512],
       [0.51314458, 0.43385435, 0.49700581, 0.54099743],
       [0.56314433, 0.47927516, 0.54441099, 0.59397023],
       [0.55283505, 0.50409522, 0.54391211, 0.60411386],
       [0.57628891, 0.48920319, 0.53842321, 0.58748939],
       [0.53247448, 0.50483994, 0.55888217, 0.58439   ],
       [0.49613402, 0.43410279, 0.51896201, 0.51986471],
       [0.52835052, 0.45842626, 0.52145702, 0.56522953],
       [0.6167527 , 0.53387928, 0.55389215, 0.60298672],
       [0.61314439, 0.53611315, 0.61352294, 0.65370522],
       [0.6342786 , 0.55994034, 0.61127737, 0.6677937 ],
       [0.61881468, 0.54877131, 0.63872248, 0.6680754 ],
       [0.53659813, 0.50235794, 0.52045896, 0.57255547],
       [0.48788672, 0.44551995, 0.53393207, 0.54212457],
       [0.49304136, 0.46190113, 0.50948085, 0.52409126],
       [0.53762912, 0.48920319, 0.50399195, 0.51901927],
       [0.5422681 , 0.46934714, 0.52894205, 0.54663282],
       [0.41546411, 0.4494911 , 0.51147698, 0.45702998],
       [0.37010334, 0.34425402, 0.43313362, 0.36122835],
       [0.34097951, 0.31298081, 0.35928139, 0.38320651],
       [0.2979384 , 0.26408543, 0.34955079, 0.33333345],
       [0.36108273, 0.29833692, 0.3343313 , 0.36066495],
       [0.45103093, 0.37428622, 0.37924147, 0.40180323],
       [0.52938151, 0.45445511, 0.46157679, 0.51084823],
       [0.50618563, 0.44452709, 0.52395203, 0.53817973],
       [0.46262887, 0.45768184, 0.49401192, 0.51169333],
       [0.53814446, 0.45644084, 0.4640718 , 0.51704702],
       [0.56932996, 0.48920319, 0.53642708, 0.60298672],
       [0.56546398, 0.51402324, 0.58383226, 0.58889824],
       [0.54768041, 0.4862249 , 0.55389215, 0.59368818],
       [0.56082499, 0.49168519, 0.54640712, 0.59847847],
       [0.57164961, 0.49813834, 0.53892209, 0.60862211],
       [0.54458775, 0.46934714, 0.55389215, 0.57086492],
       [0.53247448, 0.48821032, 0.57784418, 0.57762746],
       [0.45953621, 0.41474303, 0.48802383, 0.49704145],
       [0.43814433, 0.41722503, 0.50648696, 0.48689782],
       [0.49097938, 0.41821789, 0.4391217 , 0.47055505],
       [0.45335058, 0.42690491, 0.5       , 0.49140606],
       [0.49097938, 0.41970704, 0.42964054, 0.475345  ],
       [0.5221652 , 0.46736142, 0.49151691, 0.52409126],
       [0.68530934, 0.61578546, 0.53892209, 0.59735133],
       [0.69793827, 0.61330345, 0.68313377, 0.73485498],
       [0.76185592, 0.76222377, 0.74900178, 0.8306566 ],
       [0.78144349, 0.69818791, 0.73602785, 0.81375043],
       [0.75721662, 0.71705139, 0.78093803, 0.78726403],
       [0.77164955, 0.69719535, 0.76272434, 0.83037456],
       [0.70489691, 0.66492928, 0.7485029 , 0.75542394],
       [0.74020637, 0.65475282, 0.70858275, 0.76077763],
       [0.71675283, 0.63663436, 0.70359273, 0.76754017],
       [0.70747423, 0.62050133, 0.68862267, 0.76359533],
       [0.73866005, 0.67287158, 0.71357277, 0.80022536],
       [0.72319613, 0.6552494 , 0.73852286, 0.78331919],
       [0.78092784, 0.70488951, 0.7210578 , 0.79515337],
       [0.80541237, 0.77066265, 0.80264449, 0.84108194],
       [0.74613402, 0.7103498 , 0.75848294, 0.80867845],
       [0.7435567 , 0.66294356, 0.73478035, 0.70047889],
       [0.70747423, 0.65202267, 0.7210578 , 0.7776838 ],
       [0.83015489, 0.73988572, 0.73028921, 0.81459554],
       [0.75747429, 0.75204761, 0.82110762, 0.82896571],
       [0.75180431, 0.7115908 , 0.77295412, 0.81600438],
       [0.71185586, 0.69570591, 0.76846298, 0.73260068],
       [0.67551572, 0.61578546, 0.67365261, 0.73541838],
       [0.59510316, 0.60511271, 0.65818367, 0.65849517],
       [0.60335077, 0.52742613, 0.57584836, 0.59735133],
       [0.65927848, 0.57433609, 0.61427126, 0.68920811],
       [0.67783505, 0.5884834 , 0.63073857, 0.6942801 ],
       [0.65902081, 0.63911637, 0.6699101 , 0.7213299 ],
       [0.64948454, 0.61901218, 0.70858275, 0.71062252],
       [0.67448472, 0.59344741, 0.66816371, 0.7213299 ],
       [0.70128891, 0.63315949, 0.66866259, 0.73823607],
       [0.7528353 , 0.66641843, 0.69860271, 0.77458441],
       [0.73969072, 0.69024562, 0.7582335 , 0.81825868],
       [0.77809285, 0.68776361, 0.75349292, 0.78895458],
       [0.83608254, 0.76718778, 0.85828333, 0.86813174],
       [0.77603118, 0.80193586, 0.85828333, 0.84812617],
       [0.7922681 , 0.73641085, 0.76147683, 0.81149614],
       [0.80773202, 0.73492171, 0.79815366, 0.81318669],
       [0.85360844, 0.79200783, 0.81836317, 0.89489984],
       [1.        , 1.        , 0.9086824 , 1.        ],
       [0.98350541, 0.92429884, 1.        , 0.98901092],
       [0.70309291, 0.87043914, 0.95808372, 0.77571155],
       [0.55283505, 0.61330345, 0.6961077 , 0.60101447],
       [0.46855683, 0.47927516, 0.56886221, 0.37193573],
       [0.52190722, 0.46934714, 0.53393207, 0.51845587],
       [0.53994845, 0.47604844, 0.52145702, 0.56382069],
       [0.5128866 , 0.48250189, 0.55613772, 0.56635668],
       [0.52500019, 0.45470325, 0.54391211, 0.58269945],
       [0.51520625, 0.47431115, 0.56387219, 0.52690895],
       [0.48427841, 0.43931494, 0.50898197, 0.53733429],
       [0.5064433 , 0.43633635, 0.47255489, 0.47337275],
       [0.44819594, 0.40977902, 0.49900194, 0.49084232],
       [0.43788666, 0.3839661 , 0.47305377, 0.48182583],
       [0.42345373, 0.38992297, 0.44910174, 0.45083119],
       [0.38685592, 0.336808  , 0.42539915, 0.41307401],
       [0.31572165, 0.29511049, 0.36427141, 0.33107915],
       [0.28479381, 0.25093068, 0.3343313 , 0.30374765],
       [0.18195901, 0.23603864, 0.32435126, 0.1656806 ],
       [0.17809304, 0.13502115, 0.16467064, 0.16539855],
       [0.17551572, 0.14718273, 0.20958081, 0.19188496],
       [0.14845386, 0.10697437, 0.18962074, 0.16089031],
       [0.05489703, 0.04690996, 0.10479041, 0.07016067],
       [0.        , 0.        , 0.08507977, 0.00760764],
       [0.02345386, 0.05956813, 0.        , 0.        ],
       [0.14690722, 0.07917603, 0.08433145, 0.06762468],
       [0.12886598, 0.06626942, 0.13473052, 0.1129895 ],
       [0.11288672, 0.10871165, 0.15518948, 0.12961397],
       [0.06185567, 0.06602128, 0.1297405 , 0.07410551],
       [0.18505167, 0.12956056, 0.11976046, 0.12397858],
       [0.2371134 , 0.17920066, 0.23453091, 0.22344335],
       [0.22087648, 0.17101023, 0.25024959, 0.22541559],
       [0.19046398, 0.13154628, 0.21007969, 0.20146519],
       [0.27268054, 0.23057835, 0.25449099, 0.25415595],
       [0.30824767, 0.24100266, 0.26447103, 0.2795152 ],
       [0.31649497, 0.27078672, 0.32135737, 0.3355874 ],
       [0.30180438, 0.2804666 , 0.35429137, 0.32149892],
       [0.19484561, 0.21121859, 0.29690615, 0.20907283],
       [0.11984536, 0.08140959, 0.1644212 , 0.06818808],
       [0.07603093, 0.08711833, 0.17465068, 0.08171315],
       [0.09407216, 0.05658954, 0.10978043, 0.09016624],
       [0.14278357, 0.09456434, 0.14471056, 0.13863045],
       [0.08453621, 0.08215432, 0.16541926, 0.08143145],
       [0.10850541, 0.04542052, 0.07509973, 0.04480142],
       [0.12551565, 0.07644558, 0.14620751, 0.13524936],
       [0.10000013, 0.07024057, 0.13223551, 0.10848125],
       [0.09149485, 0.0379745 , 0.09980039, 0.09298393],
       [0.14149491, 0.10449236, 0.12450104, 0.13074111],
       [0.23324742, 0.16406049, 0.16092812, 0.17469709],
       [0.29922706, 0.22635876, 0.26447103, 0.29332197],
       [0.3907219 , 0.32489456, 0.31886236, 0.33671454],
       [0.40824749, 0.33780086, 0.35903195, 0.40011268],
       [0.40979381, 0.37453466, 0.42914166, 0.43533387],
       [0.47268048, 0.38992297, 0.42739528, 0.48013529],
       [0.47500013, 0.40506315, 0.47355296, 0.50324025],
       [0.4935567 , 0.42690491, 0.50723559, 0.53620748],
       [0.46185586, 0.41474303, 0.50399195, 0.5018314 ],
       [0.36391771, 0.34996275, 0.43313362, 0.38348821],
       [0.31726829, 0.273765  , 0.35429137, 0.34657648],
       [0.38195895, 0.34971461, 0.34680634, 0.37334458],
       [0.40463918, 0.33010671, 0.38522955, 0.39842213],
       [0.40103118, 0.35591962, 0.41442105, 0.4178643 ],
       [0.31649497, 0.29684777, 0.36926143, 0.33840509],
       [0.2757732 , 0.2529164 , 0.3343313 , 0.22654274],
       [0.52113421, 0.44452709, 0.32934128, 0.34150449]])

In [7]:
dataset=pd.DataFrame(data1,columns=["Open","High","Low","Close"])

In [8]:
dataset

         Open      High       Low     Close
0    0.491495  0.441549  0.508982  0.543815
1    0.513145  0.433854  0.497006  0.540997
2    0.563144  0.479275  0.544411  0.593970
3    0.552835  0.504095  0.543912  0.604114
4    0.576289  0.489203  0.538423  0.587489
..        ...       ...       ...       ...
138  0.404639  0.330107  0.385230  0.398422
139  0.401031  0.355920  0.414421  0.417864
140  0.316495  0.296848  0.369261  0.338405
141  0.275773  0.252916  0.334331  0.226543
142  0.521134  0.444527  0.329341  0.341504

[143 rows x 4 columns]

In [9]:
training_size = round(len(data1 ) * 0.80)
print(training_size)
X_train=dataset[:training_size]
X_test=dataset[training_size:]
print("X_train length:",X_train.shape)
print("X_test length:",X_test.shape)
y_train=dataset[:training_size]
y_test=dataset[training_size:]
print("y_train length:",y_train.shape)
print("y_test length:",y_test.shape)

114
X_train length: (114, 4)
X_test length: (29, 4)
y_train length: (114, 4)
y_test length: (29, 4)

In [10]:
import warnings
warnings.filterwarnings("ignore")

In [11]:
# creating a dictionary variable 
performance={"Model":[],"RMSE":[],"MaPe":[],"Lag":[],"Test":[]}

In [12]:
performance

{'Model': [], 'RMSE': [], 'MaPe': [], 'Lag': [], 'Test': []}

In [13]:
# splitting train and test set
test_obs = 28
train =dataset[:-test_obs]
test = dataset[-test_obs:]

In [14]:
train

         Open      High       Low     Close
0    0.491495  0.441549  0.508982  0.543815
1    0.513145  0.433854  0.497006  0.540997
2    0.563144  0.479275  0.544411  0.593970
3    0.552835  0.504095  0.543912  0.604114
4    0.576289  0.489203  0.538423  0.587489
..        ...       ...       ...       ...
110  0.190464  0.131546  0.210080  0.201465
111  0.272681  0.230578  0.254491  0.254156
112  0.308248  0.241003  0.264471  0.279515
113  0.316495  0.270787  0.321357  0.335587
114  0.301804  0.280467  0.354291  0.321499

[115 rows x 4 columns]

In [15]:
test

         Open      High       Low     Close
115  0.194846  0.211219  0.296906  0.209073
116  0.119845  0.081410  0.164421  0.068188
117  0.076031  0.087118  0.174651  0.081713
118  0.094072  0.056590  0.109780  0.090166
119  0.142784  0.094564  0.144711  0.138630
120  0.084536  0.082154  0.165419  0.081431
121  0.108505  0.045421  0.075100  0.044801
122  0.125516  0.076446  0.146208  0.135249
123  0.100000  0.070241  0.132236  0.108481
124  0.091495  0.037974  0.099800  0.092984
125  0.141495  0.104492  0.124501  0.130741
126  0.233247  0.164060  0.160928  0.174697
127  0.299227  0.226359  0.264471  0.293322
128  0.390722  0.324895  0.318862  0.336715
129  0.408247  0.337801  0.359032  0.400113
130  0.409794  0.374535  0.429142  0.435334
131  0.472680  0.389923  0.427395  0.480135
132  0.475000  0.405063  0.473553  0.503240
133  0.493557  0.426905  0.507236  0.536207
134  0.461856  0.414743  0.503992  0.501831
135  0.363918  0.349963  0.433134  0.383488
136  0.317268  0.273765  0.354291  0.346576
137  0.381959  0.349715  0.346806  0.373345
138  0.404639  0.330107  0.385230  0.398422
139  0.401031  0.355920  0.414421  0.417864
140  0.316495  0.296848  0.369261  0.338405
141  0.275773  0.252916  0.334331  0.226543
142  0.521134  0.444527  0.329341  0.341504

In [16]:
# creating the VAR model with the given lag orders and printing the AIC and BIC value from result variable
from statsmodels.tsa.api import VAR
for i in [1,2,3,4,5,6,7,8,9,10]:
     model = VAR(train)
     results = model.fit(i)
     print('Order =', i)
     print('AIC: ', results.aic)
     print('BIC: ', results.bic)
     print()

Order = 1
AIC:  -28.07729387912183
BIC:  -27.597259063614022

Order = 2
AIC:  -28.205346860941304
BIC:  -27.336444547015248

Order = 3
AIC:  -28.03995578757878
BIC:  -26.777795597334627

Order = 4
AIC:  -27.852866761525966
BIC:  -26.19297438594724

Order = 5
AIC:  -27.683290249236766
BIC:  -25.62110524263165

Order = 6
AIC:  -27.571034319145937
BIC:  -25.10190782168801

Order = 7
AIC:  -27.47211616173051
BIC:  -24.591308547411906

Order = 8
AIC:  -27.593825360225562
BIC:  -24.296503807431435

Order = 9
AIC:  -27.45885022743059
BIC:  -23.740086209236384

Order = 10
AIC:  -27.329595305452063
BIC:  -23.1843619966346

In [17]:
model

In [18]:
results

In [19]:
x = model.select_order(maxlags=12)

In [20]:
x

In [21]:
# Used to select the optimal lag order for a time series model based on the AIC (Akaike Information Criterion)
order=x.selected_orders["aic"]

In [22]:
order

2

In [23]:
result = model.fit(order)
result

In [24]:
# displays the overall summary of the result
result.summary()

  Summary of Regression Results
==================================
Model:                         VAR
Method:                        OLS
Date:           Tue, 30, Jul, 2024
Time:                     18:55:03
--------------------------------------------------------------------
No. of Equations:         4.00000    BIC:                   -27.3364
Nobs:                     113.000    HQIC:                  -27.8528
Log likelihood:           988.242    FPE:                5.63846e-13
AIC:                     -28.2053    Det(Omega_mle):     4.14988e-13
--------------------------------------------------------------------
Results for equation Open
===========================================================================
              coefficient       std. error           t-stat            prob
---------------------------------------------------------------------------
const            0.014882         0.025443            0.585           0.559
L1.Open          0.966620         0.247455            3.906           0.000
L1.High          0.171930         0.237882            0.723           0.470
L1.Low          -0.238783         0.279105           -0.856           0.392
L1.Close         0.292429         0.237126            1.233           0.217
L2.Open         -0.125721         0.329620           -0.381           0.703
L2.High         -0.426835         0.256940           -1.661           0.097
L2.Low           0.323429         0.202290            1.599           0.110
L2.Close        -0.028018         0.210960           -0.133           0.894
===========================================================================

Results for equation High
===========================================================================
              coefficient       std. error           t-stat            prob
---------------------------------------------------------------------------
const           -0.020368         0.019452           -1.047           0.295
L1.Open          0.884632         0.189190            4.676           0.000
L1.High          0.109660         0.181870            0.603           0.547
L1.Low          -0.046890         0.213388           -0.220           0.826
L1.Close         0.139617         0.181293            0.770           0.441
L2.Open          0.001056         0.252008            0.004           0.997
L2.High          0.004796         0.196442            0.024           0.981
L2.Low           0.085262         0.154660            0.551           0.581
L2.Close        -0.216989         0.161288           -1.345           0.179
===========================================================================

Results for equation Low
===========================================================================
              coefficient       std. error           t-stat            prob
---------------------------------------------------------------------------
const            0.025132         0.011776            2.134           0.033
L1.Open          0.963454         0.114530            8.412           0.000
L1.High          0.044913         0.110099            0.408           0.683
L1.Low          -0.104762         0.129178           -0.811           0.417
L1.Close         0.021774         0.109749            0.198           0.843
L2.Open          0.012444         0.152558            0.082           0.935
L2.High          0.064327         0.118920            0.541           0.589
L2.Low           0.043060         0.093626            0.460           0.646
L2.Close        -0.070970         0.097639           -0.727           0.467
===========================================================================

Results for equation Close
===========================================================================
              coefficient       std. error           t-stat            prob
---------------------------------------------------------------------------
const           -0.033942         0.021049           -1.613           0.107
L1.Open          1.456523         0.204717            7.115           0.000
L1.High         -0.290539         0.196798           -1.476           0.140
L1.Low          -0.045484         0.230902           -0.197           0.844
L1.Close         0.011955         0.196173            0.061           0.951
L2.Open          0.283472         0.272692            1.040           0.299
L2.High         -0.686438         0.212565           -3.229           0.001
L2.Low           0.293695         0.167353            1.755           0.079
L2.Close        -0.010506         0.174526           -0.060           0.952
===========================================================================

Correlation matrix of residuals
             Open      High       Low     Close
Open     1.000000  0.807427  0.496066  0.887116
High     0.807427  1.000000  0.641116  0.701526
Low      0.496066  0.641116  1.000000  0.526117
Close    0.887116  0.701526  0.526117  1.000000

In [25]:
#to get the last order rows of the train dataset,
#These rows correspond to the most recent order observations in the training set to generate forecasts
lagged_Values = train.values[-order:]
lagged_Values

array([[0.31649497, 0.27078672, 0.32135737, 0.3355874 ],
       [0.30180438, 0.2804666 , 0.35429137, 0.32149892]])

In [26]:
# This generates forecasts for the next 28 steps using the last observed values.
pred = result.forecast(y=lagged_Values,steps=28) 
pred

array([[0.30341223, 0.26186133, 0.30976585, 0.30657951],
       [0.31679844, 0.2671442 , 0.31767688, 0.31518534],
       [0.32503005, 0.27974944, 0.32813452, 0.33319779],
       [0.33630407, 0.28928478, 0.33616439, 0.34366596],
       [0.34644737, 0.29844108, 0.34692661, 0.35363918],
       [0.35498934, 0.30777684, 0.35655664, 0.36428138],
       [0.36368182, 0.31619954, 0.36489945, 0.37334591],
       [0.37194859, 0.32425281, 0.37334212, 0.38201795],
       [0.37960041, 0.33205786, 0.38133873, 0.39047598],
       [0.38691357, 0.33937419, 0.38877689, 0.39829455],
       [0.39380668, 0.3462808 , 0.39588374, 0.4056469 ],
       [0.40025456, 0.35280978, 0.40257774, 0.41259815],
       [0.40632206, 0.35893735, 0.40884758, 0.41909439],
       [0.41201593, 0.36469031, 0.41474829, 0.42518304],
       [0.41734793, 0.37009232, 0.42028547, 0.43089617],
       [0.42234567, 0.37515511, 0.42547243, 0.43624333],
       [0.42702685, 0.37989876, 0.43033476, 0.44124927],
       [0.43140869, 0.38434252, 0.43488926, 0.44593662],
       [0.43551054, 0.38850305, 0.43915296, 0.45032287],
       [0.43934945, 0.39239755, 0.44314444, 0.45442718],
       [0.44294148, 0.39604256, 0.44688015, 0.4582676 ],
       [0.44630234, 0.39945338, 0.45037576, 0.4618605 ],
       [0.44944665, 0.40264472, 0.45364649, 0.46522164],
       [0.45238811, 0.40563048, 0.45670652, 0.46836589],
       [0.45513971, 0.40842368, 0.45956918, 0.47130707],
       [0.45771361, 0.4110366 , 0.4622471 , 0.47405823],
       [0.4601212 , 0.4134808 , 0.4647521 , 0.47663159],
       [0.46237319, 0.4157671 , 0.46709526, 0.4790386 ]])

In [27]:
listt=["Close","High","Open","Low"]

In [28]:
#All the 28 forecasted values are placed in a dataframe 
preds=pd.DataFrame(pred,columns=listt)
preds

       Close      High      Open       Low
0   0.303412  0.261861  0.309766  0.306580
1   0.316798  0.267144  0.317677  0.315185
2   0.325030  0.279749  0.328135  0.333198
3   0.336304  0.289285  0.336164  0.343666
4   0.346447  0.298441  0.346927  0.353639
5   0.354989  0.307777  0.356557  0.364281
6   0.363682  0.316200  0.364899  0.373346
7   0.371949  0.324253  0.373342  0.382018
8   0.379600  0.332058  0.381339  0.390476
9   0.386914  0.339374  0.388777  0.398295
10  0.393807  0.346281  0.395884  0.405647
11  0.400255  0.352810  0.402578  0.412598
12  0.406322  0.358937  0.408848  0.419094
13  0.412016  0.364690  0.414748  0.425183
14  0.417348  0.370092  0.420285  0.430896
15  0.422346  0.375155  0.425472  0.436243
16  0.427027  0.379899  0.430335  0.441249
17  0.431409  0.384343  0.434889  0.445937
18  0.435511  0.388503  0.439153  0.450323
19  0.439349  0.392398  0.443144  0.454427
20  0.442941  0.396043  0.446880  0.458268
21  0.446302  0.399453  0.450376  0.461860
22  0.449447  0.402645  0.453646  0.465222
23  0.452388  0.405630  0.456707  0.468366
24  0.455140  0.408424  0.459569  0.471307
25  0.457714  0.411037  0.462247  0.474058
26  0.460121  0.413481  0.464752  0.476632
27  0.462373  0.415767  0.467095  0.479039

In [29]:
# the above dataframe is converted to a .csv format
preds.to_csv("varforecasted_{}.csv".format(test_obs))

In [30]:
from sklearn.metrics import mean_squared_error
rmse= round(mean_squared_error(test,pred,squared=False))
from sklearn.metrics import mean_absolute_percentage_error
mape=mean_absolute_percentage_error(test,pred)

In [31]:
rmse

0

In [32]:
mape

1.1724381824058145

In [33]:
#selected order for the model creation and its evaluation metrics are appended to the performance dictionary
performance["Model"].append(listt)
performance["RMSE"].append(rmse)
performance["MaPe"].append(mape)
performance["Lag"].append(order)
performance["Test"].append(test_obs)
# dictionary values are converted into dataframe
perf=pd.DataFrame(performance)

In [34]:
perf

                      Model  RMSE      MaPe  Lag  Test
0  [Close, High, Open, Low]     0  1.172438    2    28

## A function defined to create the VAR model with selected lag order ##

In [37]:
def cominbation(dataset,listt):
    print(listt)
    datasetTwo=dataset[listt]
    test_obs = 28
    train =datasetTwo[:-test_obs]
    test = datasetTwo[-test_obs:]
    from statsmodels.tsa.api import VAR
    for i in [1,2,3,4,5,6,7,8,9,10]:
        model = VAR(train)
        results = model.fit(i)
        print('Order =', i)
        print('AIC: ', results.aic)
        print('BIC: ', results.bic)
        print()
    x = model.select_order(maxlags=12)
    order=x.selected_orders["aic"]
    result = model.fit(order)
    #result.summary()
    lagged_Values = train.values[-order:]
    pred = result.forecast(y=lagged_Values,steps=28) 
    preds=pd.DataFrame(pred,columns=listt)
    preds.to_csv("varforecasted_{}.csv".format(test_obs))
    from sklearn.metrics import mean_squared_error
    rmse= round(mean_squared_error(test,pred,squared=False))
    from sklearn.metrics import mean_absolute_percentage_error
    mape=mean_absolute_percentage_error(test,pred)
    performance["Model"].append(listt)
    performance["RMSE"].append(rmse)
    performance["MaPe"].append(mape)
    performance["Lag"].append(order)
    performance["Test"].append(test_obs)
    perf1=pd.DataFrame(performance)
    return perf1,result,pred

In [41]:
list1=["Close","High","Open"]

In [42]:
perf1,result,pred=cominbation(dataset,list1)

['Close', 'High', 'Open']
Order = 1
AIC:  -20.219075458514407
BIC:  -19.93105456920972

Order = 2
AIC:  -20.457081793681233
BIC:  -19.9502221105577

Order = 3
AIC:  -20.40921477795537
BIC:  -19.681045437429898

Order = 4
AIC:  -20.304929756263654
BIC:  -19.352932658505267

Order = 5
AIC:  -20.22532985945052
BIC:  -19.046938427104738

Order = 6
AIC:  -20.161694030913193
BIC:  -18.754291927362175

Order = 7
AIC:  -20.0258887054788
BIC:  -18.386808511125107

Order = 8
AIC:  -19.94411201590989
BIC:  -18.070633860913226

Order = 9
AIC:  -19.8476944785112
BIC:  -17.737044630346922

Order = 10
AIC:  -19.721786786649247
BIC:  -17.37113619079544

In [43]:
perf1

                      Model  RMSE      MaPe  Lag  Test
0  [Close, High, Open, Low]     0  1.172438    2    28
1             [Close, High]     0  1.597460    2    28
2       [Close, High, Open]     0  1.382092    2    28